version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: amigo
      POSTGRES_PASSWORD: pass1233
      POSTGRES_DB: customer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  frontend:
    container_name: stag22-frontend
    build: 
      context: ../frontend/react
      args:
        api_base_url: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "3000:5173"
    networks:
      - postgres_network
    restart: unless-stopped
      
  backend:
    container_name: stag22-backend
    image: localhost:5000/homenet/stag22-api:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    #network_mode: "host"

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data: