server:
  port: 8080
  error:
    include-message: always
    
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,beans'
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
  
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  
jwtutil:
  issuer: "http://localhost"
  validity_days: 15
  
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/customer}
    username: amigo
    password: pass1233
  jpa:
    hibernate:
      ddl-auto: validate # create-drop #update - for persistent schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true #default - false
  main:
    web-application-type: SERVLET
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  codec:
    max-in-memory-size: 15MB
logging:
  level:
    org.flywaydb: DEBUG