version: '3.8'

services:
  postgres:
    container_name: postgres_512
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: amigo
      POSTGRES_PASSWORD: pass1233
      POSTGRES_DB: customer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
