name: CI - Build Backend

on:
  pull_request:
    branches: 
      - main
    paths:
      - backend/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_USER: amigo
          POSTGRES_PASSWORD: test1233
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setupjava@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run ITs with Maven
        run: mvn -ntp -B verify
